theme: jekyll-theme-slate
title: "Deep Learning Based Speed Estimation for Constraining Strapdown Inertial Navigation on Smartphones"
description: "<a href='#'>Santiago Cortés</a>, <a href='http://arno.solin.fi'>Arno Solin</a>, and <a href='https://users.aalto.fi/~kannalj1/'>Juho Kannala</a><br />Published in MLSP 2018"
