theme: jekyll-theme-slate
title: "Robust Gyroscope-Aided Camera Self-Calibration"
description: "<a href='#'>Santiago Cortes</a>, <a href='http://arno.solin.fi'>Arno Solin</a>, and <a href='https://users.aalto.fi/~kannalj1/'>Juho Kannala</a><br />Published in FUSION 2018"
